language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "pypy"
env:
  - WITHPYICU=yes
  - WITHPYICU=no

before_install:
  - pip install codecov

install:
  - travis_retry pip install .
  - pip install -r requirements.txt
  - if [[ $WITHPYICU == 'yes' ]]; then pip install PyICU; fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' && $WITHPYICU == 'yes' ]]; then echo; else nosetests; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' && $WITHPYICU == 'yes' ]]; then echo; else codecov; fi
