language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

before_install:
  - pip install codecov

install:
  - travis_retry pip install .

script:
  - nosetests

after_success:
  - codecov
